on:
  push:
    branches: 
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm install
    - name: Create Nuxt.js project
      run: npm run generate
    - name: Deploy to S3
      uses: amazon/aws-cli@latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: s3 sync ./dist s3://bluefrog.ca --delete --cache-control max-age=31536000
